// <auto-generated />
namespace EF_Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_tableDocGia : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_tableDocGia));
        
        string IMigrationMetadata.Id
        {
            get { return "201612011103406_update_tableDocGia"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
