// <auto-generated />
namespace EF_Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class version_05Nov2016 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version_05Nov2016));
        
        string IMigrationMetadata.Id
        {
            get { return "201611041805405_version_05Nov2016"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
