// <auto-generated />
namespace EF_Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_forgein_key_the_loai : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_forgein_key_the_loai));
        
        string IMigrationMetadata.Id
        {
            get { return "201610111245020_update_forgein_key_the_loai"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
